name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:  # Optional: Test changes in PRs
    branches:
      - main

# Provision API resource, build container from Dockerfile, push to DockerHub, and deploy to Azure Container Apps.
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beesafeapi:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/beesafeapi:latest

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build-and-push  # Depends on the previous job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container to Azure
        run: |
          az containerapp create \
            --name beesafe-app \
            --resource-group BeeSafe \
            --environment caebeesafe \
            --image ${{ secrets.DOCKER_USERNAME }}/beesafeapi:latest \
            --cpu 0.5 \
            --memory 1.0Gi \
            --registry-server docker.io \
            --registry-username ${{ secrets.DOCKER_USERNAME }} \
            --registry-password ${{ secrets.DOCKER_PASSWORD }} \
            --env-vars DATABASE_URL=${{ secrets.AZURE_DATABASE_URL }}

      - name: Enable Public Access (Ingress)
        run: |
          az containerapp ingress enable \
            --name beesafe-app \
            --resource-group BeeSafe \
            --type external \
            --target-port 443 \
            --transport auto

      - name: Get Public URL
        run: |
          echo "Container App URL:"
          az containerapp show \
            --name beesafe-app \
            --resource-group BeeSafe \
            --query "properties.configuration.ingress.fqdn" \
            --output tsv
