name: Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beesafeapi:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/beesafeapi:latest


  deploy:
    name: Deploy to Azure Container Instance
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Container to Azure Container Instance
      run: |
        az container create \
          --name beesafe-api-container \
          --resource-group BeeSafe \
          --image httpd:latest \
          --cpu 0.5 \
          --memory 1.0 \
          --registry-login-server docker.io \
          --registry-username ${{ secrets.DOCKER_USERNAME }} \
          --registry-password ${{ secrets.DOCKER_PASSWORD }} \
          --environment-variables DATABASE_URL=${{ secrets.AZURE_DATABASE_URL }} \
          --ports 80 \
          --ip-address public \
          --os-type Linux
          
    - name: Get Public IP
      run: |
        echo "Container Instance Public IP:"
        az container show \
          --name beesafe-api-container \
          --resource-group BeeSafe \
          --query "ipAddress.ip" \
          --output tsv