name: "CodeQL Advanced"

on:
  pull_request:
    branches:
      - main
# Analyse code on Pull Request, before pushing to main
jobs:
# CodeQL Job
 analyze:
   name: Analyze (${{ matrix.language }})
   runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
   permissions:
     security-events: write
     packages: read
     actions: read
     contents: read

   strategy:
     fail-fast: false
     matrix:
       include:
        # Languages to analyse
       - language: csharp
         build-mode: manual
         #.NET Should be build manually, will not work with autobuild 
       - language: javascript-typescript
         build-mode: none
       - language: python
         build-mode: none
       - language: actions
         build-mode: none

   steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Initialize CodeQL
     uses: github/codeql-action/init@v3
     with:
       languages: ${{ matrix.language }}
       build-mode: ${{ matrix.build-mode }}

  # Manual Build Process for .NET Application
   - name: Setup Node.js
     if: matrix.language == 'csharp'
     uses: actions/setup-node@v4
     with:
       node-version: '20'

   - name: Build C# Project
     if: matrix.language == 'csharp'
     run: |
       cd BeeSafeWeb
       npm install
       dotnet restore BeeSafeWeb/BeeSafeWeb.csproj
       dotnet build BeeSafeWeb/BeeSafeWeb.csproj -c Release
  #Start Scan
   - name: Perform CodeQL Analysis
     uses: github/codeql-action/analyze@v3