name: Deploy to Azure (Testing)
'on':
  push:
    branches:
      - test
  # Run on push to testing Branch
jobs:
  # Build the Docker image and push it to DockerHub
  build-and-push:
    name: Build and Push Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build Docker Image
        run: >-
          docker build -t ${{ secrets.DOCKER_USERNAME }}/beesafeapptest:latest
          ./BeeSafeWeb/
      - name: Push Docker Image to DockerHub
        run: 'docker push ${{ secrets.DOCKER_USERNAME }}/beesafeapptest:latest'
  # Deploy job to provision application to Azure
  deploy:
    name: Deploy to Azure Container TestInstance
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Check if MySQL TestServer exists  # Create MySQL server to be able to create database
        id: check-server-exists
        run: >
          SERVER_EXISTS=$(az mysql flexible-server show --name
          beesafe-mysql-testserver --resource-group BeeSafe --query "name" -o tsv ||
          echo "")

          echo "Server Exists: $SERVER_EXISTS"
          
          if [[ -n "$SERVER_EXISTS" ]]; then
            echo "MySQL server already exists, skipping creation."
          else
            echo "MySQL server does not exist, proceeding with creation."
            az mysql flexible-server create \
              --name beesafe-mysql-testserver \
              --resource-group BeeSafe \
              --location uksouth \
              --admin-user ${{ secrets.MYSQL_USER }} \
              --admin-password ${{ secrets.MYSQL_PASSWORD }} \
              --sku-name Standard_B1ms \
              --storage-size 32 \
              --version 8.0.21 \
              --public-access 0.0.0.0
          fi

      - name: Check if MySQL TestDatabase exists # Database to store application data
        run: |
          DB_EXISTS=$(az mysql flexible-server db list \
            --server-name beesafe-mysql-testserver \
            --resource-group BeeSafe \
            --query "[?name=='beesafe-testdb']" -o tsv)
          
          if [[ -z "$DB_EXISTS" ]]; then
            echo "Database 'beesafe-testdb' does not exist. Creating the database..."
            az mysql flexible-server db create \
              --resource-group BeeSafe \
              --server-name beesafe-mysql-testserver \
              --database-name beesafe-testdb
          else
            echo "Database 'beesafe-testdb' already exists. Skipping creation."
          fi
        
      - name: Check if Container TestApp Environment Exists # Container app environment (CAE) needed to run container app in
        run: |
          ENV_NAME="caebeesafe"
          RESOURCE_GROUP="BeeSafe"
          LOCATION="uksouth"
          EXISTING_ENV=$(az containerapp env show \
            --name $ENV_NAME \
            --resource-group $RESOURCE_GROUP \
            --query "name" \
            --output tsv || echo "none")

          if [ "$EXISTING_ENV" = "none" ]; then
            echo "Environment does not exist. Creating..."
            az containerapp env create \
              --name $ENV_NAME \
              --resource-group $RESOURCE_GROUP \
              --location $LOCATION
          else
            echo "Environment $ENV_NAME already exists. Skipping creation."
          fi
          
      - name: Deploy Container to Azure Container Instance # Deploy the container app in the CAE
        uses: nick-invision/retry@v2 # If container app fails to create, retry 2 more times
        with:
          timeout_minutes: 3
          max_attempts: 3
          retry_wait_seconds: 15
          command: |
            az containerapp create \
              --name beesafe-testapp-container \
              --resource-group BeeSafe \
              --image docker.io/${{ secrets.DOCKER_USERNAME }}/beesafetestapp:latest \
              --cpu 0.5 \
              --memory 1.0 \
              --registry-server docker.io \
              --registry-username ${{ secrets.DOCKER_USERNAME }} \
              --registry-password ${{ secrets.DOCKER_PASSWORD }} \
              --target-port 8080 \
              --env-vars ConnectionStrings__DefaultConnection="Server=tcp:dbbeesafe.database.windows.net,1433;Initial Catalog=beesafe;Persist Security Info=False;User ID=${{ secrets.MYSQL_USER }};Password=${{ secrets.MYSQL_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" \
              --ingress external \
              --environment testcaebeesafe 
          # Create container app by pulling docker image from DockerHub, open port 8080 for application, add connection string for connection with database, ingress external to make it publicly available

      - name: Get Domain Name and Save to ENV # Get domain name from application app, save it to variable for later DAST testing
        id: get-fqdn
        run: |
          # Get the FQDN of the deployed container app
          fqdn=$(az containerapp show \
            --name beesafe-testapp-container \
            --resource-group BeeSafe \
            --query "properties.configuration.ingress.fqdn" \
            --output tsv)

